#line 2 "src/lex.yy.c"

#line 4 "src/lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 69
#define YY_END_OF_BUFFER 70
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[354] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       70,   68,   67,   66,   66,   17,   55,   45,   15,   68,
       11,   21,    3,   19,    4,   14,   68,    5,   46,   46,
       23,   13,    2,    8,   45,   45,   12,   22,   27,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,    9,   68,   20,   53,   52,
       52,   53,   60,   59,   59,   56,   58,   64,   65,   64,
       61,   63,   50,   49,   49,   66,   16,   45,    1,   43,
       24,   47,    0,   51,   48,   47,    0,    0,    0,   46,
        0,   25,   10,    6,    7,   26,   45,   45,   45,   45,

       45,   45,   45,   45,   45,   45,   45,   45,   45,   43,
       45,   45,   45,   45,   45,   45,   45,   45,   33,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   18,   52,
       54,    0,   56,    0,   59,   58,   57,   65,   63,   62,
       49,   47,    0,    0,    0,   47,    0,   47,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   43,
       45,   45,   45,   34,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,

       45,   45,   45,   45,   45,    0,   47,    0,   47,    0,
       47,    0,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   32,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   44,   41,
       45,   45,   47,    0,    0,   45,   45,   45,   45,   45,
       45,   29,   45,   45,   45,   45,   43,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   43,   45,   45,   42,    0,   45,   40,   43,   45,
       45,   45,   45,   31,   45,   45,   45,   45,   45,   45,

       45,   45,   37,   38,   39,   45,   45,   45,   45,   30,
       43,    0,   45,   28,   45,   45,   45,   45,   45,   45,
       45,   45,   45,    0,    0,   45,   45,   45,   45,   45,
       45,    0,    0,   45,   45,   45,    0,    0,   45,    0,
        0,   45,    0,    0,    0,    0,    0,    0,    0,    0,
       36,   35,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    7,    8,    9,    1,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   19,   19,    1,   20,   21,
       22,   23,    1,    1,   24,   24,   24,   24,   25,   24,
       24,   24,   26,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   27,   24,   24,   24,   24,   24,   24,   24,
       28,   29,   30,   31,   32,    1,   33,   34,   35,   36,

       37,   38,   39,   40,   41,   42,   43,   44,   45,   46,
       47,   48,   42,   49,   50,   51,   52,   53,   54,   55,
       56,   57,   58,   59,   60,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[61] =
    {   0,
        1,    1,    2,    2,    1,    1,    3,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    3,    1,
        1,    1,    1,    3,    3,    3,    3,    1,    1,    1,
        1,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    1,    1,    1
    } ;

static const flex_int16_t yy_base[362] =
    {   0,
        0,    0,   58,   60,   62,   70,   74,   78,   82,   84,
      508,  509,  509,  509,  504,  484,  509,    0,  509,  496,
      509,  509,  509,  491,  509,   52,   71,   80,   77,   92,
      509,   79,  481,   82,  456,   62,  509,  509,  509,   72,
       72,   83,   32,   87,   93,  454,   98,  453,  102,   99,
      462,  101,   98,  451,  457,  509,  437,  509,  509,  509,
      492,  477,   65,  509,  490,  509,  139,  509,  509,  489,
      509,  140,  509,  509,  488,  509,  509,    0,  509,  509,
      509,  142,  453,  509,  509,  145,  176,  184,  140,  191,
      186,  509,  509,  509,  509,  509,  438,  439,  437,  436,

      435,  437,  446,  431,   99,  448,  447,  433,  440,  425,
      426,  423,  423,  429,  426,  424,  421,  418,    0,  420,
      115,  421,  415,  411,  420,  428,  115,  428,  410,  413,
      138,  411,  417,  411,   71,  163,  132,  415,  509,  509,
      509,  169,  509,  200,  509,  509,  205,  509,  509,  509,
      509,  207,  218,  203,  409,  222,  162,  224,  417,  412,
      401,  400,  413,  405,  415,  410,  409,  410,  395,  393,
      133,  409,  407,  403,  394,  401,  387,  403,  402,    0,
      387,  170,  382,  395,  392,  389,  385,  385,  374,  375,
      381,  372,  374,  371,  380,  383,  368,  383,  367,  369,

      369,  377,  377,  379,  367,  234,  239,  371,  242,  244,
      246,  250,  370,  362,  370,  357,  356,  367,  360,  362,
      351,  349,  358,  346,  353,    0,  350,  358,  350,  342,
      355,  342,  357,  340,  335,  354,  353,  348,  343,  334,
      331,  340,  345,  330,  343,  337,  322,  325,    0,    0,
      323,  336,  254,  262,  321,  334,  331,  324,  335,  316,
      333,    0,  319,  320,  326,  326,  317,  315,  308,  312,
      319,  319,  316,  303,  318,  317,  305,  315,  298,  308,
      298,  296,  304,  303,    0,  303,  293,    0,  325,  305,
      293,  286,  286,    0,  286,  279,  297,  298,  299,  294,

      293,  278,    0,    0,    0,  290,  280,  289,  281,  509,
      308,  276,  271,    0,  284,  274,  282,  283,  280,  268,
      268,  265,  271,  245,  240,  240,  243,  252,  252,  246,
      234,  251,  232,  227,  237,  213,  217,  239,  213,  198,
      197,  194,  190,  175,  194,  171,  154,  147,   74,   47,
      509,  509,  509,  294,  297,  300,  303,   80,  306,  309,
      312
    } ;

static const flex_int16_t yy_def[362] =
    {   0,
      353,    1,  354,  354,  355,  355,  356,  356,  357,  357,
      353,  353,  353,  353,  353,  353,  353,  358,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  358,  358,  353,  353,  353,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  353,  353,  353,  353,  353,
      353,  353,  359,  353,  353,  353,  360,  353,  353,  353,
      353,  361,  353,  353,  353,  353,  353,  358,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  358,  358,  358,  358,

      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  353,  353,
      353,  359,  353,  353,  353,  353,  359,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,

      358,  358,  358,  358,  358,  353,  353,  353,  353,  353,
      353,  353,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  353,  353,  353,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  353,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,

      358,  358,  358,  358,  358,  358,  358,  358,  358,  353,
      358,  353,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  353,  353,  358,  358,  358,  358,  358,
      358,  353,  353,  358,  358,  358,  353,  353,  358,  353,
      353,  358,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,    0,  353,  353,  353,  353,  353,  353,  353,
      353
    } ;

static const flex_int16_t yy_nxt[570] =
    {   0,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
       32,   33,   34,   18,   18,   35,   36,   37,   12,   38,
       39,   18,   40,   41,   42,   43,   44,   45,   46,   18,
       47,   18,   18,   48,   18,   49,   18,   50,   51,   52,
       53,   18,   54,   55,   18,   18,   18,   56,   57,   58,
       60,   61,   60,   61,   64,   65,   80,   66,  109,   62,
      143,   62,   64,   65,   81,   66,   69,   70,  110,   71,
       69,   70,   78,   71,   74,   75,   74,   75,   82,   82,
       67,   84,   86,  144,   87,   87,   85,  352,   67,   92,

       93,   88,   72,   95,   96,  100,   72,   86,   89,   90,
       90,  199,   98,   88,   83,  105,   88,   99,  102,  200,
      103,  101,  106,   91,  351,  114,  107,  104,   88,  108,
      111,  126,  112,  115,  123,  119,  116,  135,  124,  117,
      130,  113,  120,  121,  147,  150,  136,  127,  167,  168,
      128,  131,  132,  125,  133,  189,  134,   87,   87,  152,
      152,  190,  156,  156,  183,  184,  153,  147,  150,  153,
      194,   89,  203,  154,  143,  204,  147,  150,  153,  158,
      158,  153,  222,  223,  147,  150,  195,  147,  150,  147,
      150,   86,  350,   87,   87,  201,  157,  144,  157,  349,

       88,  158,  158,   90,   90,  142,   86,   89,   90,   90,
      143,  348,   88,  231,  202,   88,  232,   91,  180,  347,
      152,  152,   91,  346,  152,  152,  345,   88,  142,  180,
      206,  153,  206,  144,  154,  207,  207,  142,  154,  209,
      209,  211,  211,  153,  344,  142,  153,  343,  142,  342,
      142,  207,  207,  210,  341,  212,  253,  253,  153,  209,
      209,  209,  209,  211,  211,  340,  153,  211,  211,  339,
      254,  253,  253,  210,  180,  210,  180,  212,  153,  253,
      253,  212,  338,  337,  180,  254,  336,  180,  180,  335,
      334,  333,  332,  254,   59,   59,   59,   63,   63,   63,

       68,   68,   68,   73,   73,   73,  142,  180,  142,  146,
      331,  146,  149,  330,  149,  180,  329,  328,  327,  326,
      180,  180,  325,  324,  323,  322,  321,  320,  319,  180,
      180,  318,  317,  316,  180,  180,  180,  315,  314,  313,
      312,  311,  310,  309,  308,  180,  307,  180,  306,  305,
      304,  303,  302,  301,  300,  180,  299,  298,  180,  297,
      296,  295,  294,  293,  292,  291,  180,  290,  289,  288,
      287,  286,  285,  284,  283,  282,  281,  280,  180,  279,
      278,  180,  277,  276,  275,  274,  273,  272,  271,  270,
      269,  268,  180,  267,  249,  266,  265,  264,  263,  180,

      262,  180,  180,  261,  260,  259,  258,  257,  256,  255,
      252,  251,  250,  249,  248,  247,  180,  246,  245,  244,
      243,  242,  241,  240,  239,  238,  237,  236,  180,  235,
      180,  234,  233,  180,  230,  229,  228,  227,  180,  226,
      225,  224,  221,  180,  220,  180,  180,  219,  218,  217,
      216,  215,  214,  213,  208,  205,  198,  197,  196,  193,
      192,  191,  188,  187,  180,  186,  185,  182,  181,  180,
      179,  178,  177,  176,  175,  174,  173,  172,  171,  170,
      169,  166,  165,  164,  163,  162,  161,  160,  159,  155,
      151,  148,  145,  141,  140,  139,  138,  137,  129,  122,

      118,   97,   94,   80,   79,   77,   76,  353,   11,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353
    } ;

static const flex_int16_t yy_chk[570] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    3,    4,    4,    5,    5,   26,    5,   43,    3,
       63,    4,    6,    6,   26,    6,    7,    7,   43,    7,
        8,    8,  358,    8,    9,    9,   10,   10,   27,   27,
        5,   28,   29,   63,   29,   29,   28,  350,    6,   32,

       32,   29,    7,   34,   34,   40,    8,   30,   29,   30,
       30,  135,   36,   29,   27,   42,   30,   36,   41,  135,
       41,   40,   42,   30,  349,   45,   42,   41,   30,   42,
       44,   50,   44,   45,   49,   47,   45,   53,   49,   45,
       52,   44,   47,   47,   67,   72,   53,   50,  105,  105,
       50,   52,   52,   49,   52,  127,   52,   89,   89,   82,
       82,  127,   86,   86,  121,  121,   82,   67,   72,   86,
      131,   89,  137,   82,  142,  137,   67,   72,   82,  157,
      157,   86,  171,  171,   67,   72,  131,   67,   72,   67,
       72,   87,  348,   87,   87,  136,   88,  142,   88,  347,

       87,   88,   88,   91,   91,  144,   90,   87,   90,   90,
      147,  346,   87,  182,  136,   90,  182,   91,  136,  345,
      154,  154,   90,  344,  152,  152,  343,   90,  144,  342,
      153,  152,  153,  147,  154,  153,  153,  144,  152,  156,
      156,  158,  158,  152,  341,  144,  156,  340,  144,  339,
      144,  206,  206,  156,  338,  158,  207,  207,  156,  209,
      209,  210,  210,  211,  211,  337,  209,  212,  212,  336,
      207,  253,  253,  209,  335,  210,  334,  211,  209,  254,
      254,  212,  333,  332,  331,  253,  330,  329,  328,  327,
      326,  325,  324,  254,  354,  354,  354,  355,  355,  355,

      356,  356,  356,  357,  357,  357,  359,  323,  359,  360,
      322,  360,  361,  321,  361,  320,  319,  318,  317,  316,
      315,  313,  312,  311,  309,  308,  307,  306,  302,  301,
      300,  299,  298,  297,  296,  295,  293,  292,  291,  290,
      289,  287,  286,  284,  283,  282,  281,  280,  279,  278,
      277,  276,  275,  274,  273,  272,  271,  270,  269,  268,
      267,  266,  265,  264,  263,  261,  260,  259,  258,  257,
      256,  255,  252,  251,  248,  247,  246,  245,  244,  243,
      242,  241,  240,  239,  238,  237,  236,  235,  234,  233,
      232,  231,  230,  229,  228,  227,  225,  224,  223,  222,

      221,  220,  219,  218,  217,  216,  215,  214,  213,  208,
      205,  204,  203,  202,  201,  200,  199,  198,  197,  196,
      195,  194,  193,  192,  191,  190,  189,  188,  187,  186,
      185,  184,  183,  181,  179,  178,  177,  176,  175,  174,
      173,  172,  170,  169,  168,  167,  166,  165,  164,  163,
      162,  161,  160,  159,  155,  138,  134,  133,  132,  130,
      129,  128,  126,  125,  124,  123,  122,  120,  118,  117,
      116,  115,  114,  113,  112,  111,  110,  109,  108,  107,
      106,  104,  103,  102,  101,  100,   99,   98,   97,   83,
       75,   70,   65,   62,   61,   57,   55,   54,   51,   48,

       46,   35,   33,   24,   20,   16,   15,   11,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "src/jucompiler.l"
#line 3 "src/jucompiler.l"
    // Joao Emanuel Sousa Moreira 2020230563
    // Tomas Cerveira da Cruz Pinto 2020224069

    // Yacc includes
    #include "ast.h"
    #include "y.tab.h"
    

    #define TOKEN(flag, ...) if (flag) printf(__VA_ARGS__); if (flag) printf("\n")
    #define ERROR(...) printf(__VA_ARGS__);printf("\n")

    int col=1, line=1;
    int savecol, saveline;
    extern bool l;

    #define findAsciiChars(character, line, col) { if (character <= 126 && character >= 33) printf("Line %d, col %d: illegal character (%c)\n", line, col, character); }
    #define SEND_TOKEN(...) {  yylval.token = token(yytext, __VA_ARGS__); return __VA_ARGS__; }
    
    extern bool syntax_error; 

#line 706 "src/lex.yy.c"

#line 708 "src/lex.yy.c"

#define INITIAL 0
#define COMMENT 1
#define STR 2
#define INVALID_STR 3
#define COM 4

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 94 "src/jucompiler.l"


#line 932 "src/lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 354 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 509 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 96 "src/jucompiler.l"
{ TOKEN(l, "AND");                    col+=yyleng; SEND_TOKEN(AND      ); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 97 "src/jucompiler.l"
{ TOKEN(l, "ASSIGN");                 col+=yyleng; SEND_TOKEN(ASSIGN   ); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 98 "src/jucompiler.l"
{ TOKEN(l, "STAR");                   col+=yyleng; SEND_TOKEN(STAR     ); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 99 "src/jucompiler.l"
{ TOKEN(l, "COMMA");                  col+=yyleng; SEND_TOKEN(COMMA    ); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 100 "src/jucompiler.l"
{ TOKEN(l, "DIV");                    col+=yyleng; SEND_TOKEN(DIV      ); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 101 "src/jucompiler.l"
{ TOKEN(l, "EQ");                     col+=yyleng; SEND_TOKEN(EQ       ); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 102 "src/jucompiler.l"
{ TOKEN(l, "GE");                     col+=yyleng; SEND_TOKEN(GE       ); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 103 "src/jucompiler.l"
{ TOKEN(l, "GT");                     col+=yyleng; SEND_TOKEN(GT       ); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 104 "src/jucompiler.l"
{ TOKEN(l, "LBRACE");                 col+=yyleng; SEND_TOKEN(LBRACE   ); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 105 "src/jucompiler.l"
{ TOKEN(l, "LE");                     col+=yyleng; SEND_TOKEN(LE       ); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 106 "src/jucompiler.l"
{ TOKEN(l, "LPAR");                   col+=yyleng; SEND_TOKEN(LPAR     ); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 107 "src/jucompiler.l"
{ TOKEN(l, "LSQ");                    col+=yyleng; SEND_TOKEN(LSQ      ); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 108 "src/jucompiler.l"
{ TOKEN(l, "LT");                     col+=yyleng; SEND_TOKEN(LT       ); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 109 "src/jucompiler.l"
{ TOKEN(l, "MINUS");                  col+=yyleng; SEND_TOKEN(MINUS    ); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 110 "src/jucompiler.l"
{ TOKEN(l, "MOD");                    col+=yyleng; SEND_TOKEN(MOD      ); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 111 "src/jucompiler.l"
{ TOKEN(l, "NE");                     col+=yyleng; SEND_TOKEN(NE       ); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 112 "src/jucompiler.l"
{ TOKEN(l, "NOT");                    col+=yyleng; SEND_TOKEN(NOT      ); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 113 "src/jucompiler.l"
{ TOKEN(l, "OR");                     col+=yyleng; SEND_TOKEN(OR       ); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 114 "src/jucompiler.l"
{ TOKEN(l, "PLUS");                   col+=yyleng; SEND_TOKEN(PLUS     ); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 115 "src/jucompiler.l"
{ TOKEN(l, "RBRACE");                 col+=yyleng; SEND_TOKEN(RBRACE   ); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 116 "src/jucompiler.l"
{ TOKEN(l, "RPAR");                   col+=yyleng; SEND_TOKEN(RPAR     ); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 117 "src/jucompiler.l"
{ TOKEN(l, "RSQ");                    col+=yyleng; SEND_TOKEN(RSQ      ); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 118 "src/jucompiler.l"
{ TOKEN(l, "SEMICOLON");              col+=yyleng; SEND_TOKEN(SEMICOLON); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 119 "src/jucompiler.l"
{ TOKEN(l, "ARROW");                  col+=yyleng; SEND_TOKEN(ARROW    ); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 120 "src/jucompiler.l"
{ TOKEN(l, "LSHIFT");                 col+=yyleng; SEND_TOKEN(LSHIFT   ); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 121 "src/jucompiler.l"
{ TOKEN(l, "RSHIFT");                 col+=yyleng; SEND_TOKEN(RSHIFT   ); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 122 "src/jucompiler.l"
{ TOKEN(l, "XOR");                    col+=yyleng; SEND_TOKEN(XOR      ); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 123 "src/jucompiler.l"
{ TOKEN(l, "BOOL");                   col+=yyleng; SEND_TOKEN(BOOL     ); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 124 "src/jucompiler.l"
{ TOKEN(l, "CLASS");                  col+=yyleng; SEND_TOKEN(CLASS    ); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 125 "src/jucompiler.l"
{ TOKEN(l, "DOTLENGTH");              col+=yyleng; SEND_TOKEN(DOTLENGTH); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 126 "src/jucompiler.l"
{ TOKEN(l, "DOUBLE");                 col+=yyleng; SEND_TOKEN(DOUBLE   ); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 127 "src/jucompiler.l"
{ TOKEN(l, "ELSE");                   col+=yyleng; SEND_TOKEN(ELSE     ); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 128 "src/jucompiler.l"
{ TOKEN(l, "IF");                     col+=yyleng; SEND_TOKEN(IF       ); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 129 "src/jucompiler.l"
{ TOKEN(l, "INT");                    col+=yyleng; SEND_TOKEN(INT      ); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 130 "src/jucompiler.l"
{ TOKEN(l, "PRINT");                  col+=yyleng; SEND_TOKEN(PRINT    ); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 131 "src/jucompiler.l"
{ TOKEN(l, "PARSEINT");               col+=yyleng; SEND_TOKEN(PARSEINT ); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 132 "src/jucompiler.l"
{ TOKEN(l, "PUBLIC");                 col+=yyleng; SEND_TOKEN(PUBLIC   ); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 133 "src/jucompiler.l"
{ TOKEN(l, "RETURN");                 col+=yyleng; SEND_TOKEN(RETURN   ); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 134 "src/jucompiler.l"
{ TOKEN(l, "STATIC");                 col+=yyleng; SEND_TOKEN(STATIC   ); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 135 "src/jucompiler.l"
{ TOKEN(l, "STRING");                 col+=yyleng; SEND_TOKEN(STRING   ); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 136 "src/jucompiler.l"
{ TOKEN(l, "VOID");                   col+=yyleng; SEND_TOKEN(VOID    ); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 137 "src/jucompiler.l"
{ TOKEN(l, "WHILE");                  col+=yyleng; SEND_TOKEN(WHILE    ); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 138 "src/jucompiler.l"
{ TOKEN(l, "RESERVED(%s)", yytext);   col+=yyleng; SEND_TOKEN(RESERVED ); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 139 "src/jucompiler.l"
{ TOKEN(l, "BOOLLIT(%s)", yytext);    col+=yyleng; SEND_TOKEN(BOOLLIT  ); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 142 "src/jucompiler.l"
{ TOKEN(l, "ID(%s)", yytext);         col+=yyleng; SEND_TOKEN(ID       ); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 143 "src/jucompiler.l"
{ TOKEN(l, "INTLIT(%s)", yytext);     col+=yyleng; SEND_TOKEN(INTLIT   ); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 144 "src/jucompiler.l"
{ TOKEN(l, "REALLIT(%s)", yytext);    col+=yyleng; SEND_TOKEN(REALLIT  ); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 147 "src/jucompiler.l"
{ BEGIN COM; }
	YY_BREAK
case 49:
/* rule 49 can match eol */
YY_RULE_SETUP
#line 148 "src/jucompiler.l"
{ BEGIN 0; line++; col = 1; }
	YY_BREAK
case YY_STATE_EOF(COM):
#line 149 "src/jucompiler.l"
{ BEGIN 0; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 150 "src/jucompiler.l"
{ ; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 152 "src/jucompiler.l"
{ savecol = col; saveline = line; col+= yyleng; BEGIN COMMENT; }
	YY_BREAK
case 52:
/* rule 52 can match eol */
YY_RULE_SETUP
#line 153 "src/jucompiler.l"
{ col = 1; line++; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 154 "src/jucompiler.l"
{ col += yyleng; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 155 "src/jucompiler.l"
{ col += yyleng; BEGIN 0; }
	YY_BREAK
case YY_STATE_EOF(COMMENT):
#line 156 "src/jucompiler.l"
{ ERROR("Line %d, col %d: unterminated comment", saveline, savecol); BEGIN 0; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 159 "src/jucompiler.l"
{ savecol = col; saveline = line; col+= yyleng; BEGIN STR; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 160 "src/jucompiler.l"
{ TOKEN(l, "STRLIT(\"%s)", yytext); col += yyleng; BEGIN 0; SEND_TOKEN(STRLIT); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 161 "src/jucompiler.l"
{ col += yyleng; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 162 "src/jucompiler.l"
{ ERROR("Line %d, col %d: invalid escape sequence (%s)", line, col, yytext); col += yyleng; BEGIN INVALID_STR; }
	YY_BREAK
case YY_STATE_EOF(STR):
#line 163 "src/jucompiler.l"
{ ERROR("Line %d, col %d: unterminated string literal", saveline, savecol); line++; col = 1; BEGIN 0; }
	YY_BREAK
case 59:
/* rule 59 can match eol */
YY_RULE_SETUP
#line 164 "src/jucompiler.l"
{ ERROR("Line %d, col %d: unterminated string literal", saveline, savecol); line++; col = 1; BEGIN 0; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 165 "src/jucompiler.l"
{ col += yyleng; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 167 "src/jucompiler.l"
{ BEGIN 0; col+= yyleng; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 168 "src/jucompiler.l"
{ col += yyleng; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 169 "src/jucompiler.l"
{ ERROR("Line %d, col %d: invalid escape sequence (%s)", line, col, yytext);col += yyleng; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 170 "src/jucompiler.l"
{ col += yyleng; }
	YY_BREAK
case 65:
/* rule 65 can match eol */
YY_RULE_SETUP
#line 171 "src/jucompiler.l"
{ ERROR("Line %d, col %d: unterminated string literal", saveline, savecol); line++; col = 1; BEGIN 0; }
	YY_BREAK
case YY_STATE_EOF(INVALID_STR):
#line 172 "src/jucompiler.l"
{ ERROR("Line %d, col %d: unterminated string literal", saveline, savecol); line++; col = 1; BEGIN 0; }
	YY_BREAK
case 66:
/* rule 66 can match eol */
YY_RULE_SETUP
#line 176 "src/jucompiler.l"
{ line++; col=1; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 177 "src/jucompiler.l"
{ col+= 1; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 178 "src/jucompiler.l"
{ findAsciiChars(*yytext, line, col) col+=yyleng; }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 179 "src/jucompiler.l"
{ return 0; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 182 "src/jucompiler.l"
ECHO;
	YY_BREAK
#line 1359 "src/lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 354 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 354 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 353);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 182 "src/jucompiler.l"

/*int main(int argc, char *argv[]) {

    for (int i = 0; i < argc; ++i) {
        if (!strcmp(argv[i], "-l"))
            l = true;
        else l = false;
    }

    yylex();
    return 0;
}*/

int yywrap() {
    return 1;
}


extern void yyerror (const char *s ) {
    if (!yytext[0]) {
        printf ("Line %d, col %d: %s: %s\n", line, col, s , yytext);
    } else if (yytext[yyleng-1] == '"') {
        printf ("Line %d, col %d: %s: \"%s\n", line, col - yyleng-1, s , yytext );
    } else {
        printf ("Line %d, col %d: %s: %s\n", line, col - yyleng, s , yytext );
    }
    syntax_error = true;
}

